import Image from "next/image";
import { BiSolidUserPlus } from "react-icons/bi";
import Table from "../components/table";
import Form from "@/components/form";

export default function Home() {
  return (
    <>
      <head>
        <title>SmartShift</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <main className="py-5">
          <h1 className="text-xl md:text-5xl text-center font-bold py-10">
            SMARTSHIFT
          </h1>
          <div className="container mx-auto flex justify-between py-5 border-b">
            <div className="left flex gap-3">
              <button className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800">
                Add Employee{" "}
                <span className="px-1">
                  <BiSolidUserPlus size={25}></BiSolidUserPlus>
                </span>
              </button>
            </div>
          </div>

          {/*collapsable form*/}
          <div className="container mx-auto py-5">
            <Form></Form>
          </div>

          {/*table*/}
          <div className="container mx-auto">
            <Table></Table>
          </div>
        </main>
      </body>
    </>
  );
}
